### ISSUE TITLE
viewWillAppear is loaded before viewDidLoad

### ISSUE THREAD

**Issue by chlebta** [uacaps/PageMenu#71]
Hello, I've noticed strange behavior for this library in the first Item (viewController) in the controllerArray.
The problem is that viewWillAppear is executed before viewDidLoad, When I set this same viewcontroller as the second or third ... object in the controllerArray then it work fine and viewDidLoad is executed first.
 I'm the Objective-C classe from the  StoryBoard Example.

**Comment by vespid** [comment]
I faced the same issue.
The problem is that PageMenu doesn't fully support ContainerViewController interface.
(CAPSPageMenu calls its childViewController's viewWillAppear() directly that it shouldn't do)

#### Quick fix:

You can fix this issue by calling viewDidLoad() before CAPSPageMenu calls viewController.viewWillAppear()

```swift
		let viewController = UIViewController()
		let hoge = viewController.view	// dummy variable(it will be never used): to load viewController.view & it automatically calls viewController.viewDidLoad()
		
		var controllerArray : [UIViewController] = []
		controllerArray.append(viewController)
		
		pageMenu = CAPSPageMenu(viewControllers: controllerArray, frame: frame, pageMenuOptions: parameters) // inside the init method CAPSPageMenu calls viewController.viewWillAppear()

```

**Comment by fabdarice** [comment]
Hi I'm having a similar problem but not exactly.
viewWillAppear is never called on my first viewController. When I swipe to the 2nd, third or come back to the first one, it will successfully call viewWillAppear. However, it's never called on the first viewControlller,  any idea ? I've tried your method above but it didn't work

**Comment by vespid** [comment]
Hi
I think you initialize CAPSPageMenu using init(viewControllers: frame: options:)
If it's the case, use init(viewControllers: frame: pageMenuOptions:)

**Comment by fabdarice** [comment]
No I'm already using the init with pageMenuOptions.
See https://gist.github.com/fabdarice/4cd0755aa6dc0555db45

**Comment by vespid** [comment]
The viewController that viewWillAppear is not called, is activeMatchupsVC, right?
And are you using v1.2.8?
https://github.com/uacaps/PageMenu/tree/1.2.8

About v1.2.8's demo projects, the first child viewController's viewWillAppear does get called, so it sounds weird

If the version is 1.2.8 and the implementation looks properly, it's very discouraged idea but you can force call viewWillAppear like:

```swift
        self.view.addSubview(pageMenu!.view)
        activeMatchupsVC.viewWillAppear(false)
```

**Comment by fabdarice** [comment]
First of all, thanks for taking your time to help me.
The viewController is indeed ActiveMatchupVC for which the function viewWillAppear ins't called the first time.
I've used the latest version, however, since I'm on Swift 2, when I've used the automatic conversion tools to make CAPSPageMenu.swift compatible. Here's what it looks like after : https://gist.github.com/fabdarice/6e899f88a02dfa049fbd

Using the same version, when I run in the demo project, viewWillAppear doesn't get called the first time.

**Comment by vespid** [comment]
Ok the version you're using is not 1.2.8, it's current master.
So in MatchupsVC.viewDidLoad, replace (1) to (2)

```swift
        // (1)
        self.view.addSubview(pageMenu!.view)
```

```swift
        // (2) // there may be spelling mistakes
        self.addChildViewController(pageMenu)

        pageMenu.view.frame = self.view.bounds // modify this line as you like
        pageMenu.view.autoresizingMask = [UIViewAutoresizing.FlexibleWidth, UIViewAutoresizing.FlexibleHeight] // modify this line as you like

        self.view.addSubview(pageMenu!.view)
        pageMenu.didMoveToParentViewController(self)
```

#### Description:

In the latest code, CAPSPageMenu adds its child viewControllers to the viewController hierarchy, it means the system automatically calls view appearance methods like viewWillAppear.
So as you can see in the (2) code, you have to add pageMenu to the hierarchy

For more explanation, google "iOS ViewController hierarchy" or "shouldAutomaticallyForwardAppearanceMethods"

**Comment by fabdarice** [comment]
ok so, I've modified (1) to (2) and here's what I see : 
- With the master branch, viewWillAppear still isn't called.
- With the older 1.2.8, viewWillAppear is called, however, it's called before viewDidLoad and the swipe left/right doesn't work anymore, you have to click on the menu item to select the viewController.

**Comment by fabdarice** [comment]
Nevermind, with the master branch, viewWillAppear is not called.
However, it seems it didn't solve my issue.
Let me illustrate it for you. The first time the viewController is called, my view isn't properly displayed (see image : http://i63.tinypic.com/33cam51.png), however, after I swipe right to 2nd viewController then back to the first one, it is now properly displayed (see image : http://tinypic.com/view.php?pic=waq782&s=9#.VkRSM66rTUo)

This viewController is using autolayout constraint and I'm accessing it from somewhere else in my app without any display issues.
Do you have any idea why with PageMenu I'm facing those issues??

**Comment by vespid** [comment]
```swift
        // in CAPSPageMenu.addPageAtIndex()

        newVC.view.frame = CGRectMake(self.view.frame.width * CGFloat(index), menuHeight, self.view.frame.width, self.view.frame.height - menuHeight)
        newVC.view.autoresizingMask = [UIViewAutoresizing.FlexibleWidth, UIViewAutoresizing.FlexibleHeight] // add this line
```

should fix it

**Comment by fabdarice** [comment]
You are a life saver... Thank you so much, been struggling with this for days..
Really really appreciate it thanks !

**Comment by vespid** [comment]
:+1:

**Comment by DesmondDAI** [comment]
Still encounter this problem in version 2.0.0 using Swift 3. Quick fix by calling reference of view controller's root view, as illustrated by @mitsuyoshi-yamazaki
